name: Test

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  checks: write
  actions: read
  contents: read

env:
  TEST_RESULTS_FILE: testResults.xml
  TEST_RESULTS_ARTIFACT: test-results

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Run Tests
      id: run-tests
      run: ./RunTests.ps1

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: ${{ env.TEST_RESULTS_ARTIFACT }}
        path: ${{ env.TEST_RESULTS_FILE }}
        if-no-files-found: warn

    # https://github.com/HylandSoftware/unit-test-reporter
    - name: Hyland Unit Test Reporter
      id: hyland-unit-test-reporter
      uses: HylandSoftware/unit-test-reporter@d5f22dffa6970046350d036d57e6bc2e45e260b5 # v3.0.0
      if: success() || failure()
      with:
        path: "${{ env.TEST_RESULTS_FILE }}"
        report-title: "Hyland Unit Test Reporter"
        reportType: 'junit'
        access-token: ${{secrets.GITHUB_TOKEN}}

    - name: After Hyland Reporter
      run: |
        echo "This should not run after Hyland Reporter sees a test failure."
        echo "Run Tests"
        echo "Conclusion: ${{ steps.run-tests.conclusion }}"
        echo "Outcome: ${{ steps.run-tests.outcome }}"
        echo "Hyland Unit Test Reporter"
        echo "Conclusion: ${{ steps.hyland-unit-test-reporter.conclusion }}"
        echo "Outcome: ${{ steps.hyland-unit-test-reporter.outcome }}"

    # https://github.com/marketplace/actions/test-reporter
    - name: Dorny Test Reporter
      id: dorny-test-reporter
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: '${{ env.TEST_RESULTS_ARTIFACT }}'
        name: 'Dorny Test Reporter'
        path: ${{ env.TEST_RESULTS_FILE }}
        reporter: 'java-junit'
        fail-on-error: 'true'
        fail-on-empty: 'true'

    - name: Echo Conclusion and Outcome
      if: success() || failure()
      run: |
        echo "Run Tests"
        echo "Conclusion: ${{ steps.run-tests.conclusion }}"
        echo "Outcome: ${{ steps.run-tests.outcome }}"
        echo "Hyland Unit Test Reporter"
        echo "Conclusion: ${{ steps.hyland-unit-test-reporter.conclusion }}"
        echo "Outcome: ${{ steps.hyland-unit-test-reporter.outcome }}"
        echo "Dorny Test Reporter"
        echo "Conclusion: ${{ steps.dorny-test-reporter.conclusion }}"
        echo "Outcome: ${{ steps.dorny-test-reporter.outcome }}"

    - name: After All
      run: |
        echo "This should only run after all tests have passed."
