name: Test

on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types: [opened, reopened, synchronize, ready_for_review, labeled]

permissions:
  checks: write
  actions: read
  contents: read

env:
  TEST_RESULTS_FILE: testResults.xml
  TEST_RESULTS_ARTIFACT: test-results


jobs:
  test:
    runs-on: windows-latest # For Linux, use ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Run Tests
      run: ./RunTests.ps1

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TEST_RESULTS_ARTIFACT }}
        path: ${{ env.TEST_RESULTS_FILE }}
        if-no-files-found: warn

    - name: Hyland Unit Test Reporter
      uses: HylandSoftware/unit-test-reporter@d5f22dffa6970046350d036d57e6bc2e45e260b5 # v3.0.0
      if: success() || failure()
      with:
        path: "${{ env.TEST_RESULTS_FILE }}"
        report-title: "Hyland Unit Test Reporter"
        reportType: 'junit'
        access-token: ${{secrets.GITHUB_TOKEN}}

    - name: MirageNet NUnit Reporter
      uses: MirageNet/nunit-reporter@v1.1.0
      if: success() || failure()
      with:
        path: ${{ env.TEST_RESULTS_FILE }}
        reportTitle: "MirageNet NUnit Reporter"
        access-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Dorny Test Reporter
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        artifact: '${{ env.TEST_RESULTS_ARTIFACT }}'
        name: 'Dorny Test Reporter'
        path: ${{ env.TEST_RESULTS_FILE }}
        reporter: 'java-junit'
        fail-on-error: 'true'
        fail-on-empty: 'true'
